import { NricTypesMm } from './index.interface';
import { getDistrictsByState } from '.';

const MyanmarNumbers =
  '\u1040\u1041\u1042\u1043\u1044\u1045\u1046\u1047\u1048\u1049';
const MyanmarCharacters =
  '\u1000\u1001\u1002\u1003\u1004\u1005\u1006\u1007\u1008\u100A\u100E\u100F\u1010\u1011\u1012\u1013\u1014\u1015\u1016\u1017\u1018\u1019\u101A\u101B\u101C\u101D\u101E\u101F\u1020\u1025\u1027';

export const regx_eng =
  /^([\d]{1,2})\/(?:AHGAYA|AHKHAKA|AHPANA|BAMANA|HAKHANA|HAPANA|KAMANA|KAMATA|KATANA|KHABADA|KHATADA|LAGANA|LAKHANA|LAMANA|MAAHNA|MABANA|MABAPA|MAGADA|MAHTANA|MAKAHTA|MAKAKA|MAKANA|MAKATA|MAKAYA|MAKHABA|MAMANA|MANYANA|MASANA|NAMANA|OUMANA|PABATA|PAKATA|PANYANA|PATAAH|SADANA|SALANA|SaPaBa|TANANA|THATANA|WAMANA|YAKANA|YANAKA|AHLANA|BALAKHA|DAMASA|DAMATHA|GALANA|KALANA|KALAWA|KAWANA|LAKANA|LAMATA|MAGATA|MAYANA|OUKALA|PATAKA|PHASANA|PHAYASA|YATANA|AHAHNA|BAAHNA|BAKASA|BALANA|BATHASA|KASAKA|LABANA|LASANA|LATHANA|MAWATA|NATALA|PAAHNA|PAKANA|PHAAHNA|PHAPANA|TAAHNA|TAKANA|TASAKA|TATANA|TAYANA|THAHTANA|THAKANA|THATAKA|DAMANA|HTATALA|KAKANA|KAPALA|KAWALA|MALANA|MAMAKA|MATANA|MATAPA|PALANA|PALAWA|PHALANA|TATALA|TAZANA|YAZANA|AHTANA|AHYATA|AHYATHA|BATALA|DAKANA|DAPAYA|HAMALA|HTAKHANA|HTAOUTA|KABALA|KALAHTA|KALATA|KALATHA|KANANA|KASANA|KATALA|KATHANA|KHAMANA|KHAOUKA|KHAOUNA|KHAOUTA|KHAPANA|KHATANA|LAWANA|LAYANA|LAHANA|MAMATA|MAMAYA|MAYAKA|NAYANA|NGAZANA|NYANANA|PALABA|PALATHA|PAPHANA|PAYANA|SAKANA|SAKAPA|SAKAYA|SALAKA|SATHANA|TAMANA|TANGANA|TASANA|TATHANA|THAKAKA|THAKALA|WALANA|WATHANA|YAAHNA|YABANA|YAHTANA|YAMAPA|YAOUNA|YATAYA|YATHANA|YATHAYA|BAAHYA|BAPANA|HTAWANA|KALAAH|KAPANA|KATHATA|KAYANA|KAYAYA|KHAMAKA|LALANA|MAAHYA|MALALA|MATAYA|PAKAMA|PALATA|PANALA|PATANA|PATHANA|PHAMANA|TADANA|TAGANA|TAPANA|TATHAYA|TAWANA|THAYAKHA|WAHTANA|WAKANA|YAPANA|YAPHANA|AHBANA|AHMANA|AHPHANA|AHPHANGA|BATANA|DAOUNA|HTATAPA|KAHTAKHA|KAKAKHA|KAKAPA|KAKAYA|KAMAKA|KANGANA|KAPAKA|KAPATA|KATAKHA|LAPANA|LAPATA|MAKHANA|NYALAPA|PADANA|PAKHANA|PAKHATA|PAMANA|PASANA|PATAKHA|PATATA|PAWAKA|PAZANA|PHAKHANA|PHAOUNA|PHATANA|SAKHANA|SAMANA|TATAKHA|THALAPA|THALAWA|THANAPA|THAPANA|THAWAKA|THAWANA|THAWATA|WAKHAMA|WATANA|YAKATA|YAMANA|YAMATA|YAPATA|ZAKANA|AHMAYA|BAYANA|GAGANA|HAMANA|HTALANA|KATAKA|KATATA|MAKHAKA|MANAMA|MATHANA|NALANA|NAMAOU|NAPANA|NGAPHANA|PAKHAKA|SAPANA|SAPAWA|SAPHANA|SATAKA|SATAYA|TAKAKA|TATAKA|THALANA|THAYANA|WAKHAKA|YAMAKA|YANAKHA|YAOUMA|YASAKA|AHDANA|AHMAZA|DAKHATHA|DANATHA|KABANA|KAKHATA|KAMAKANA|KAPABA|KAWATA|KHAAHZA|KHAMAKHA|KHAMASA|MAAHZA|MAHAMA|MAHTALA|MANAKA|MANALA|MANATA|MAOULA|MAPANA|MAPHANA|MATALA|MATAMA|MATHAKA|MATHAYA|MAYABA|MAYAMA|MAYAPA|MAYATA|MAYATHA|NAHTAKA|NATAKA|NGATHAYA|NYAOULA|NYAOUNA|OUTATHA|PABANA|PABATHA|PAKAKHA|PAKASA|PAOULA|PATALA|PATHAKA|PAAULA|SAKATA|SATANA|SATATA|TAKATA|TANA|TAPATA|TATAOU|THADANA|THAKAMA|THAKHAKA|THAPATA|THASANA|THAYAPA|YAMATHA|ZABATHA|ZAPATHA|ZAYATHA|ZAZANA|KAHTANA|KAMAYA|KHASANA|KHAZANA|MADANA|MAKAMA|MALAKHA|MALAMA|MALATA|MAOUNA|PHAPAYA|TAPHANA|THABAYA|THAHTALA|THAKHAYA|THAMAYA|THAPHAYA|YAPAYA|ZALAMA|BATATHA|BATHATA|DADANA|DATAGA|GALAMA|GAMANA|KAPHANA|MAAHTA|MAGANA|MAPAMA|MAPATA|OUHTATHA|PANAKA|PANATA|PATAPA|PATHATA|TAPAWA|YATHATA|AHGANA|AHGATA|AHHTAKA|AHKHANA|AHLAKA|AHMATA|AHSANA|AHSAYA|AHTHANA|BABATA|BADANA|BAGATA|BAHANA|BAHATA|BAHTAHTA|BAKALA|BAKATA|BALABA|BALABNA|BAPATA|BATAHTA|BATAKA|BATATA|BAYAKA|DADAYA|DAGAMA|DAGANA|DAGASA|DAGATA|DAGAYA|DAKATA|DAKHANA|DALANA|DANAMA|DANAPA|DANAPHA|DAPANA|DAPHANA|DAYANA|GAHANA|HATHATA|HTAKANA|HTAMANA|HTATAMA|HTATATA|HTATHANA|KABATA|KAHTAHTA|KAHTAKA|KAKAKA|KAKHAKA|KAKHANA|KAKHAYA|KAMAHTA|KAMALA|KATHAYA|KHAGATA|KHAKHANA|KHAYAHA|KHAYAKA|KHAYANA|LAAHNA|LAHTANA|LAKAPA|LAKATA|LAMAKA|LAMATHA|LAMAYA|LATANA|LATAPA|LATATA|LATHAMA|LATHATHA|LATHAYA|MAAHPA|MABATA|MADAGA|MAGAKA|MAGALA|MAGAWA|MAHANA|MATAHTA|MATAKA|MATANYA|MATATA|MAZATA|NAKATA|NAKAYA|OUKAHTA|OUKAKA|OUKAMA|OUKANA|OUKAPA|OUKATA|OUPATA|OUTAKA|OUTAMA|OUTATA|OUTHATA|PAAHTA|PABAKA|PAGATA|PASATA|PAYATA|PAZATA|PHAHANA|SAGANA|SAKAKHA|SAKHAGA|SAKHAMA|SAPAYA|SAZANA|TABATA|TAGATA|TAHTANA|TAHTAPA|TAKHALA|TAKHANA|TAMA|TAMATA|TATAHTA|TATAPA|TATATA|THAGAKA|THAGANA|THAGATA|THAKAGA|THAKATA|THAKHANA|THALAKA|THALATA|THALAYA|THAMANA|THANYAKA|THATATA|YAKAMA|YALANA|YAPATHA|YATHAPA|YAYAKHA|BASANA|HAPAMA|HAPATA|KAHANA|KAKHALA|KALADA|KATAYA|KATHAHA|LAKAYA|LAKHATA|LALAYA|LANANA|MAHAYA|MANANA|MANGANA|MAPHATA|MASAKA|MASALA|MASATA|NAKHAMA|NAKHANA|NAKHATA|NAMAKA|NAMATA|NASANA|NASATA|NATAYA|NAPHANA|NGASANA|NYAKANA|NYAYANA|PATAYA|PATHAYA|PAWANA|SASANA|TAHANA|TAKHAKA|TALANA|TAMANYA|TASALA|THANANA|YAKASA|YAKHANA|YANGANA|YASANA|YASAYA|AHGADA|AHGAPA|AHKHAMA|BATHANA|DAGAPA|GATHATA|HAKAKA|HATHANA|HTAKAKA|KAKAHTA|KAKALA|KAKATA|KAPAYA|KHALANA|MAAHMA|MAAHPHA|MAGAPA|MAKALA|MAPAKA|NGAPATA|NGATHAKHA|NGAYAKA|NYANATA|NYATANA|PAMANA|PAPHAMA|PASALA|SAKALA|SANAMA|SANAPHA|TAKALA|TAKHAMA|TALATA|TATHATA|THAKHAMA|ZALANA|)\((?:N|E|V|P|THA|THI)\)([\d]{6})$/i;

export const regx_mm = new RegExp(
  '^([' +
    MyanmarNumbers +
    ']{1,2})/([' +
    MyanmarCharacters +
    ']{3}|[' +
    MyanmarCharacters +
    ']{6})[(](?:' +
    NricTypesMm.N +
    '|' +
    NricTypesMm.E +
    '|' +
    NricTypesMm.P +
    ')[)]([' +
    MyanmarNumbers +
    ']{6})$'
);

const StatesMm: Record<string, string> = {
  '\u1000': 'KA',
  '\u1001': 'KHA',
  '\u1002': 'GA',
  '\u1003': 'GHA',
  '\u1004': 'NGA',
  '\u1005': 'CA',
  '\u1006': 'CHA',
  '\u1007': 'ZA',
  '\u1008': 'JHA',
  '\u1009': 'NYA',
  '\u100A': 'NNYA',
  '\u100B': 'TTA',
  '\u100C': 'TTHA',
  '\u100E': 'DDA',
  '\u100F': 'NNA',
  '\u1010': 'TA',
  '\u1011': 'THA',
  '\u1012': 'DA',
  '\u1013': 'DHA',
  '\u1014': 'NA',
  '\u1015': 'PA',
  '\u1016': 'PHA',
  '\u1017': 'BA',
  '\u1018': 'BHA',
  '\u1019': 'MA',
  '\u101A': 'YA',
  '\u101B': 'RA',
  '\u101C': 'LA',
  '\u101D': 'WA',
  '\u101E': 'SA',
  '\u101F': 'HA',
  '\u1020': 'LLA',
  '\u1021': 'A',
  '\u1022': 'SHAN A',
  '\u1023': 'I',
  '\u1024': 'II',
  '\u1025': 'U',
  '\u1026': 'UU',
  '\u1027': 'E',
  '\u1028': 'MON E',
  '\u1029': 'O',
  '\u102A': 'AU',
};

const StatesEn: Record<string, string> = {
  KA: '\u1000',
  KHA: '\u1001',
  GA: '\u1002',
  GHA: '\u1003',
  NGA: '\u1004',
  CA: '\u1005',
  CHA: '\u1006',
  ZA: '\u1007',
  JHA: '\u1008',
  NYA: '\u1009',
  NNYA: '\u100A',
  TTA: '\u100B',
  TTHA: '\u100C',
  DDA: '\u100E',
  NNA: '\u100F',
  TA: '\u1010',
  THA: '\u1011',
  DA: '\u1012',
  DHA: '\u1013',
  NA: '\u1014',
  PA: '\u1015',
  PHA: '\u1016',
  BA: '\u1017',
  BHA: '\u1018',
  MA: '\u1019',
  YA: '\u101A',
  RA: '\u101B',
  LA: '\u101C',
  WA: '\u101D',
  SA: '\u101E',
  HA: '\u101F',
  LLA: '\u1020',
  A: '\u1021',
  'SHAN A': '\u1022',
  I: '\u1023',
  II: '\u1024',
  U: '\u1025',
  UU: '\u1026',
  E: '\u1027',
  'MON E': '\u1028',
  O: '\u1029',
  AU: '\u102A',
};

export function convertEn(nric: string) {
  let _res = '';
  nric = nric.trim();
  for (let i = 0; i < nric.length; i++) {
    if (nric[i] === '/' || nric[i] === '(' || nric[i] === ')') {
      _res += nric[i];
    } else {
      const index = MyanmarNumbers.indexOf(nric[i]);
      if (index > -1) {
        _res += index;
      } else {
        if (StatesMm[nric[i]]) _res += StatesMm[nric[i]];
      }
    }
  }
  _res = _res.replace('NANGA', 'N');
  return _res;
}

export function convertMm(nric: string) {
  let _res = '';
  nric = nric.trim();

  const startIndex = nric.indexOf('/');
  const endIndex = nric.indexOf('(');

  const state = nric.split('/')[0];

  const districts = getDistrictsByState(parseFloat(state));

  const extracted = nric.substring(startIndex + 1, endIndex).trim();

  const district = districts.find((d) => d.en === extracted);

  if (!district) throw new Error('Invalid Nric');

  nric = nric.replace(extracted, '');

  for (let i = 0; i < nric.length; i++) {
    if (nric[i] === '/' || nric[i] === '(' || nric[i] === ')') {
      _res += nric[i];
    } else {
      const index = parseFloat(nric[i]);
      if (!isNaN(index)) {
        _res += MyanmarNumbers[index];
      } else {
        if (nric[i] in NricTypesMm) {
          // @ts-expect-error No hack
          _res += NricTypesMm[nric[i]];
        }
      }
    }
  }

  const tempRes = _res.split('/');
  _res = tempRes[0] + '/' + district.mm + tempRes[1];
  return _res;
}
